package testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import org.junit.*;
// Generated by ComTest END

import reseptikirja.Aines;
import reseptikirja.Lukija;
import reseptikirja.Reseptikirja;

/**
 * Test class made by ComTest
 * @version 2018.04.16 23:35:05 // Generated by ComTest
 *
 */
public class AineksetTest {



  // Generated by ComTest BEGIN
  /** testGetAinesIdGeneraattori53 */
  @Test
  public void testGetAinesIdGeneraattori53() {    // Ainekset: 53
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    Reseptikirja reseptikirja = new Reseptikirja(); 
    assertEquals("From: Ainekset line: 59", 0, reseptikirja.getAineksetLuokka().getAinesIdGeneraattori()); 
    Aines aines = new Aines(reseptikirja.getAineksetLuokka(),"peruna",true,true,true); 
    Aines aines1 = new Aines(reseptikirja.getAineksetLuokka(),"peruna",true,true,true); 
    assertEquals("From: Ainekset line: 62", 2, reseptikirja.getAineksetLuokka().getAinesIdGeneraattori()); 
    aines.setGluteeniton(true); 
    aines1.setGluteeniton(true); 
    lukija.poistaTiedostot(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLaskeTaulukonAlkiot118 */
  @Test
  public void testLaskeTaulukonAlkiot118() {    // Ainekset: 118
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    Reseptikirja reseptikirja = new Reseptikirja(); 
    assertEquals("From: Ainekset line: 124", 0, reseptikirja.getAineksetLuokka().laskeTaulukonAlkiot()); 
    Aines aines = new Aines(reseptikirja.getAineksetLuokka(), "vesi", true, true, true); 
    reseptikirja.getAineksetLuokka().lisaaAinesTaulukkoon(aines); 
    assertEquals("From: Ainekset line: 127", 1, reseptikirja.getAineksetLuokka().laskeTaulukonAlkiot()); 
    reseptikirja.getAineksetLuokka().lisaaAinesTaulukkoon(aines); 
    assertEquals("From: Ainekset line: 129", 2, reseptikirja.getAineksetLuokka().laskeTaulukonAlkiot()); 
    lukija.poistaTiedostot(); 
  } // Generated by ComTest END
}