package testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import org.junit.*;
// Generated by ComTest END

import reseptikirja.Lukija;

/**
 * Test class made by ComTest
 * @version 2018.04.16 23:31:33 // Generated by ComTest
 *
 */
public class LukijaTest {



  // Generated by ComTest BEGIN
  /** testLueTiedosto73 */
  @Test
  public void testLueTiedosto73() {    // Lukija: 73
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    lukija.luoTiedosto(lukija.getReseptit()); 
    lukija.luoTiedosto(lukija.getAinekset()); 
    lukija.luoTiedosto(lukija.getOhjeet()); 
    lukija.tallennaTiedostoon(lukija.getReseptit(), "Toimii!"); 
    lukija.tallennaTiedostoon(lukija.getOhjeet(), "Toimii!"); 
    lukija.tallennaTiedostoon(lukija.getAinekset(), "Toimii!"); 
    String eka = lukija.lueTiedosto(lukija.getReseptit()); 
    String toka = lukija.lueTiedosto(lukija.getOhjeet()); 
    String kolmas = lukija.lueTiedosto(lukija.getAinekset()); 
    lukija.poistaTiedostot(); 
    assertEquals("From: Lukija line: 90", "Toimii!\n", eka); 
    assertEquals("From: Lukija line: 91", "Toimii!\n", toka); 
    assertEquals("From: Lukija line: 92", "Toimii!\n", kolmas); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTallennaIdTiedostoon128 */
  @Test
  public void testTallennaIdTiedostoon128() {    // Lukija: 128
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    lukija.luoTiedosto(lukija.getReseptit()); 
    lukija.luoTiedosto(lukija.getAinekset()); 
    lukija.luoTiedosto(lukija.getOhjeet()); 
    lukija.tallennaIdTiedostoon(lukija.getReseptit(), "3"); 
    lukija.tallennaIdTiedostoon(lukija.getOhjeet(), "1"); 
    lukija.tallennaIdTiedostoon(lukija.getAinekset(), "2"); 
    lukija.tallennaTiedostoon(lukija.getReseptit(), "Toimii!"); 
    lukija.tallennaTiedostoon(lukija.getOhjeet(), "Toimii!"); 
    lukija.tallennaTiedostoon(lukija.getAinekset(), "Toimii!"); 
    String eka = lukija.lueTiedosto(lukija.getReseptit()); 
    String toka = lukija.lueTiedosto(lukija.getOhjeet()); 
    String kolmas = lukija.lueTiedosto(lukija.getAinekset()); 
    lukija.poistaTiedostot(); 
    assertEquals("From: Lukija line: 149", "3\nToimii!\n", eka); 
    assertEquals("From: Lukija line: 150", "1\nToimii!\n", toka); 
    assertEquals("From: Lukija line: 151", "2\nToimii!\n", kolmas); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTallennaTiedostoon193 */
  @Test
  public void testTallennaTiedostoon193() {    // Lukija: 193
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    lukija.luoTiedosto(lukija.getReseptit()); 
    lukija.luoTiedosto(lukija.getAinekset()); 
    lukija.luoTiedosto(lukija.getOhjeet()); 
    lukija.tallennaTiedostoon(lukija.getReseptit(), "Toimii!"); 
    lukija.tallennaTiedostoon(lukija.getOhjeet(), "Toimii!"); 
    lukija.tallennaTiedostoon(lukija.getAinekset(), "Toimii!"); 
    lukija.tallennaTiedostoon(lukija.getReseptit(), "Toimii!"); 
    lukija.tallennaTiedostoon(lukija.getOhjeet(), "Toimii!"); 
    lukija.tallennaTiedostoon(lukija.getAinekset(), "Toimii!"); 
    String eka = lukija.lueTiedosto(lukija.getReseptit()); 
    String toka = lukija.lueTiedosto(lukija.getOhjeet()); 
    String kolmas = lukija.lueTiedosto(lukija.getAinekset()); 
    lukija.poistaTiedostot(); 
    assertEquals("From: Lukija line: 214", "Toimii!\nToimii!\n", eka); 
    assertEquals("From: Lukija line: 215", "Toimii!\nToimii!\n", toka); 
    assertEquals("From: Lukija line: 216", "Toimii!\nToimii!\n", kolmas); 
  } // Generated by ComTest END
}