package testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import org.junit.*;
// Generated by ComTest END

import reseptikirja.Lukija;
import reseptikirja.Ohje;
import reseptikirja.Reseptikirja;

/**
 * Test class made by ComTest
 * @version 2018.04.17 14:53:41 // Generated by ComTest
 *
 */
public class OhjeTest {



  // Generated by ComTest BEGIN
  /** testToString46 */
  @Test
  public void testToString46() {    // Ohje: 46
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    Reseptikirja rk = new Reseptikirja(); 
    Ohje ohje = new Ohje(rk.getOhjeetLuokka()); 
    assertEquals("From: Ohje line: 53", "1|", ohje.toString()); 
    ohje.setOhje("Keitä"); 
    assertEquals("From: Ohje line: 55", "1|Keitä", ohje.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParseOhje70 */
  @Test
  public void testParseOhje70() {    // Ohje: 70
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    Reseptikirja rk = new Reseptikirja(); 
    Ohje ohje = new Ohje(rk.getOhjeetLuokka()); 
    assertEquals("From: Ohje line: 77", "1|", ohje.toString()); 
    ohje.parseOhje("55567|Keitä perunat ja paista makkarinot"); 
    assertEquals("From: Ohje line: 79", "55567|Keitä perunat ja paista makkarinot", ohje.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetOhje93 */
  @Test
  public void testGetOhje93() {    // Ohje: 93
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    Reseptikirja reseptikirja = new Reseptikirja(); 
    Ohje ohje1 = new Ohje(reseptikirja.getOhjeetLuokka()); 
    Ohje ohje2 = new Ohje(reseptikirja.getOhjeetLuokka()); 
    assertEquals("From: Ohje line: 101", "", reseptikirja.getOhjeetLuokka().getOhjeet().get(0).getOhje()); 
    ohje1.setOhje("Testi1"); 
    ohje2.setOhje("Testi2"); 
    assertEquals("From: Ohje line: 106", "Testi1", reseptikirja.getOhjeetLuokka().getOhjeet().get(0).getOhje()); 
    assertEquals("From: Ohje line: 107", "Testi2", reseptikirja.getOhjeetLuokka().getOhjeet().get(1).getOhje()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetOhjeId119 */
  @Test
  public void testSetOhjeId119() {    // Ohje: 119
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    Reseptikirja reseptikirja = new Reseptikirja(); 
    Ohje ohje1 = new Ohje(reseptikirja.getOhjeetLuokka()); 
    assertEquals("From: Ohje line: 126", 1, ohje1.getOhjeId()); 
    ohje1.setOhjeId(4444); 
    assertEquals("From: Ohje line: 128", 4444, ohje1.getOhjeId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetOhje140 */
  @Test
  public void testSetOhje140() {    // Ohje: 140
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    Reseptikirja reseptikirja = new Reseptikirja(); 
    Ohje ohje1 = new Ohje(reseptikirja.getOhjeetLuokka()); 
    assertEquals("From: Ohje line: 147", "", ohje1.getOhje()); 
    ohje1.setOhje("Keitä"); 
    assertEquals("From: Ohje line: 149", "Keitä", ohje1.getOhje()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetOhjeId161 */
  @Test
  public void testGetOhjeId161() {    // Ohje: 161
    Lukija lukija = new Lukija(); 
    lukija.poistaTiedostot(); 
    Reseptikirja reseptikirja = new Reseptikirja(); 
    Ohje ohje1 = new Ohje(reseptikirja.getOhjeetLuokka()); 
    Ohje ohje2 = new Ohje(reseptikirja.getOhjeetLuokka()); 
    assertEquals("From: Ohje line: 169", 1, ohje1.getOhjeId()); 
    assertEquals("From: Ohje line: 170", 2, ohje2.getOhjeId()); 
    ohje1.setOhjeId(4444); 
    assertEquals("From: Ohje line: 172", 4444, ohje1.getOhjeId()); 
  } // Generated by ComTest END
}